### ISSUE TITLE
Apex

### ISSUE THREAD

**Issue by decanmalaj** [InstinctEx/ReChecker#3] opened 2024-01-23 22:43 UTC
Do you know how Apex is checking for reWASD and do you reckon you will be implementing a bypass for it?

**Comment by InstinctEx** [comment] 2024-01-25 10:36
I think it checks for the driver and since I don't have access to the driver's source code to rebuild it with different signature I'm not sure I can implement something.

**Comment by InstinctEx** [comment] 2024-01-26 19:38
Closing this since its a duplicate of #1

**Closed as completed by InstinctEx** 2024-01-26 19:38 UTC
Labels: duplicate, question
